spring.application.name=weple

server.port=8073

# DataSource : Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@3.34.91.19:1521:xe
spring.datasource.username=memo
spring.datasource.password=memo

# Mybatis : Default Setting, Override
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.type-aliases-package=com.weple.cloud
mybatis.mapper-locations=classpath:mapper/*/*.xml

# logging
logging.level.com.yedam.app=debug

#JPA Basic Setting
# SQL, Display
spring.jpa.show-sql=true
# SQL, Easy Reading
spring.jpa.properties.hibernate.format_sql=true
# No Vender DDL
spring.jpa.generate-ddl=true
# JPA Databalse Setting
spring.jpa.database=oracle

#master key
jasypt.encryptor.password=we+people+platform
